name: "Build docs"
description: "Install prerequisites and build CSE documentation"
runs:
  using: composite
  steps:
    - name: Install pandoc
      run: 'choco install -y pandoc --version=1.17.2 --ia=ALLUSERS=1'
      shell: bash
    - name: Add pandoc to path
      run: echo "C:\Program Files (x86)\Pandoc" >> $GITHUB_PATH
      shell: bash
    - name: Add MSVC developer commands to PATH
      uses: ilammy/msvc-dev-cmd@v1
    - name: Set build to NOT do coverage check by default
      run: rake set_coverage_off_by_default
      shell: bash
      working-directory: doc
    - name: Build docs
      run: rake
      shell: bash
      working-directory: doc
