repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    # Run the formatter (automatically fixes in-place)
    - id: ruff-format
    # Run the linter
    - id: ruff
      args: [ --fix ]
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: uv run mypy
      require_serial: true
      language: system
      types: [python]