title: Input Data
nav:
  - index.md
  - TOP Members: top-members.md
  - HOLIDAY: holiday.md
  - DESCOND: descond.md
  - MATERIAL: material.md
  - CONSTRUCTION: construction.md
  - FOUNDATION: foundation.md
  - FNDBLOCK: fndblock.md
  - LAYER: layer.md
  - GLAZETYPE: glazetype.md
  - METER: meter.md
  - DHWMETER: dhwmeter.md
  - AFMETER: afmeter.md
  - LOADMETER: loadmeter.md
  - ZONE: zone.md
  - GAIN: gain.md
  - SURFACE: surface.md
  - WINDOW: window.md
  - SHADE: shade.md
  - SGDIST: sgdist.md
  - DOOR: door.md
  - PERIMETER: perimeter.md
  - TERMINAL: terminal.md
  - IZXFER: izxfer.md
  - DOAS: doas.md
  - RSYS: rsys.md
  - DUCTSEG: ductseg.md
  - PERFORMANCEMAP: performancemap.md
  - DHWDAYUSE: dhwdayuse.md
  - DHWUSE: dhwuse.md
  - DHWSYS: dhwsys.md
  - DHWHEATER: dhwheater.md
  - DHWLOOPHEATER: dhwloopheater.md
  - DHWHEATREC: dhwheatrec.md
  - DHWTANK: dhwtank.md
  - DHWPUMP: dhwpump.md
  - DHWLOOP: dhwloop.md
  - DHWLOOPPUMP: dhwlooppump.md
  - DHWLOOPSEG: dhwloopseg.md
  - DHWLOOPBRANCH: dhwloopbranch.md
  - DHWSOLARSYS: dhwsolarsys.md
  - DHWSOLARCOLLECTOR: dhwsolarcollector.md
  - PVARRAY: pvarray.md
  - SHADEX: shadex.md
  - BATTERY: battery.md
  - AIRHANDLER: airhandler.md
  - HEATPLANT: heatplant.md
  - BOILER: boiler.md
  - COOLPLANT: coolplant.md
  - CHILLER: chiller.md
  - TOWERPLANT: towerplant.md
  - REPORTFILE: reportfile.md
  - REPORT: report.md
  - REPORTCOL: reportcol.md
  - EXPORTFILE: exportfile.md
  - EXPORT: export.md
  - EXPORTCOL: exportcol.md
  - IMPORTFILE: importfile.md