/* UNTAB.CPP: units table source file automatically generated by rcdef.exe. */

   /* do not edit this file -- it is written over any time rcdef is run --
      instead change the input, units.def, and re-run rcdef. */


#include "cnglob.h"
#include "srd.h"	// declares variable(s) defined here


/* Unit systems */

int Nunsys = 2;			// number of unit systems (2)
const char* UnsysNames[] = { "IP", "SI", NULL };	// unit system names
int Unsysext = 0;			// unit system currently in effect: used in cvpak.cpp


/* Unit types table */

UNIT Untab[] =
{ //                -------unsys 1--------   	            -------unsys 2--------
  //                printName       factor   	            printName       factor
  //                ---------       ------   	            ---------       ------
  { { {                  "",        1.00 },	{                  "",        1.00 } } }, 	// UNNONE
  { { {                 "F",        1.00 },	{                 "C",  0.55555556 } } }, 	// UNTEMP
  { { {                 "R",        1.00 },	{                 "K",       5./9. } } }, 	// UNABSTEMP
  { { {                 "F",        1.00 },	{                 "C",  0.55555556 } } }, 	// UNTDIFF
  { { {               "Btu",        1.00 },	{                "kJ",       1.055 } } }, 	// UNENERGY
  { { {              "kBtu",       0.001 },	{                "MJ",    0.001055 } } }, 	// UNENERGY1
  { { {              "MBtu",    0.000001 },	{                "GJ", 0.000001055 } } }, 	// UNENERGY2
  { { {                "Wh",       0.293 },	{                "Wh",       0.293 } } }, 	// UNENERGY3
  { { {               "kWh",    0.000293 },	{               "kWh",    0.000293 } } }, 	// UNENERGY4
  { { {           "Btu/ft2",        1.00 },	{             "kJ/m2",     11.3559 } } }, 	// UNENERGYDEN
  { { {                 "W",       0.293 },	{                 "W",       0.293 } } }, 	// UNELPWR1
  { { {                "kW",    0.000293 },	{                "kW",    0.000293 } } }, 	// UNELPWR2
  { { {              "Btuh",        1.00 },	{                 "W",       0.293 } } }, 	// UNPOWER
  { { {             "kBtuh",       0.001 },	{                "kW",    0.000293 } } }, 	// UNPOWER1
  { { {             "MBtuh",    0.000001 },	{                "MW", 0.000000293 } } }, 	// UNPOWER2
  { { {           "Btu/day",        24.0 },	{           "kWh/day",     0.00703 } } }, 	// UNPOWER3
  { { {           "kBtu/yr",      8.7600 },	{            "kWh/yr",     2.56668 } } }, 	// UNPOWER4
  { { {             "Wh/yr",     2566.68 },	{             "Wh/yr",     2566.68 } } }, 	// UNPOWER5
  { { {               "bhp", 0.000392752 },	{                "hp", 0.000398199 } } }, 	// UNBHP
  { { {             "ft-in",        1.00 },	{                "mm",      304.80 } } }, 	// UNLENGTH
  { { {                "in",       12.00 },	{                "mm",      304.80 } } }, 	// UNLENGTH2
  { { {                "ft",        1.00 },	{                "mm",      304.80 } } }, 	// UNLENGTH3
  { { {               "ft2",        1.00 },	{                "m2",      0.0929 } } }, 	// UNAREA
  { { {               "in2",       144.0 },	{               "cm2",       929.0 } } }, 	// UNAREA2
  { { {               "ft3",        1.00 },	{                "m3",      0.0283 } } }, 	// UNVOLUME
  { { {               "deg",    180./kPi },	{               "deg",    180./kPi } } }, 	// UNANGLE
  { { {          "Btuh/ft2",        1.00 },	{              "W/m2",        3.15 } } }, 	// UNPOWERDEN
  { { {             "W/ft2",      0.2926 },	{              "W/m2",        3.15 } } }, 	// UNWATTDEN
  { { {       "Btu/ft2-day",       24.00 },	{         "Wh/m2-day",        75.6 } } }, 	// UNPOWERDEN2
  { { {           "ft2/ton",        1.00 },	{             "m2/kW",      0.0264 } } }, 	// UNDENPOWER
  { { {             "W/ft2",       0.293 },	{              "W/m2",        3.15 } } }, 	// UNELECDEN
  { { { "kBtu/ft2 (source)",        1.00 },	{    "MJ/m2 (source)",        11.4 } } }, 	// UNANNUSE
  { { {            "lb/ft3",        1.00 },	{             "kg/m3",       16.00 } } }, 	// UNDENSITY
  { { {            "lb/ft2",        1.00 },	{             "kg/m2",        4.88 } } }, 	// UNDENSITY2
  { { {          "Btu/lb-F",        1.00 },	{           "kJ/kg-K",        4.19 } } }, 	// UNSPECHEAT
  { { {             "Btu/F",        1.00 },	{              "kJ/K",        1.90 } } }, 	// UNHEATCAP
  { { {         "Btu/F-ft2",        1.00 },	{           "kJ/K-m2",       20.45 } } }, 	// UNHEATCAP_AREA
  { { {         "Btu/F-ft3",        1.00 },	{           "kJ/K/m3",       67.10 } } }, 	// UNHEATCAP_VOL
  { { {            "Btu/lb",        1.00 },	{             "kJ/kg",     2.32444 } } }, 	// UNENTH
  { { {        "Btuh/ft2-F",        1.00 },	{            "W/m2-C",        5.68 } } }, 	// UNUVAL
  { { {     "Btuh-ft/ft2-F",        1.00 },	{             "W/m-C",       1.731 } } }, 	// UNCNDVY
  { { {            "Btuh/F",        1.00 },	{               "W/C",      0.5277 } } }, 	// UNUA
  { { {        "ft2-F/Btuh",        1.00 },	{            "m2-C/W",       0.176 } } }, 	// UNRVAL
  { { {      "ft2-F/Btuh-f",        1.00 },	{          "m2-C/W-m",       .5777 } } }, 	// UNRESVY
  { { {         "Btuh/ft-F",        1.00 },	{             "W/m-C",        1.73 } } }, 	// UNF2
  { { {               "ach",        1.00 },	{               "ach",        1.00 } } }, 	// UNAIRCHANGE
  { { {           "in2/ft2",        1.00 },	{            "mm2/m2",        6944 } } }, 	// UNELA
  { { {               "cfm",        1.00 },	{               "L/s",       0.472 } } }, 	// UNAIRFLOW
  { { {             "lb/hr",        1.00 },	{             "kg/hr",    0.453593 } } }, 	// UNMFLOW
  { { {            "in H2O",        1.00 },	{                "Pa",         249 } } }, 	// UNPRESAIR
  { { {            "ft H2O",        1.00 },	{               "kPa",        2.99 } } }, 	// UNPRESH2O
  { { {               "gpm",        1.00 },	{               "L/s",      0.0631 } } }, 	// UNH2OFLOW
  { { {               "fpm",        1.00 },	{               "m/s",     0.00508 } } }, 	// UNVELOCITY
  { { {                "hr",        1.00 },	{                "hr",        1.00 } } }, 	// UNHOURS
  { { {             "deg N",     57.2958 },	{             "deg N",     57.2958 } } }, 	// UNLATITUDE
  { { {             "deg W",     57.2958 },	{             "deg W",     57.2958 } } }, 	// UNLONGITUDE
  { { {             "in 12",       12.00 },	{             "in 10",       10.00 } } }, 	// UNPITCH
  { { {               "mph",        1.00 },	{              "km/h",        1.61 } } }, 	// UNWINDVEL
  { { {               "gal",     7.47943 },	{                 "l",     28.2821 } } }, 	// UNLVOLUME
  { { {               "gal",        1.00 },	{                 "l",     3.78541 } } }, 	// UNLVOLUME2
  { { {               "ton", 0.000083333 },	{                "kW",    0.000293 } } }, 	// UNTON
  { { {          "cfm/Btuh",        1.00 },	{          "(L/s)/kJ",       0.498 } } }, 	// UNCFMXPOW
  { { {          "gpm/Btuh",        1.00 },	{          "(L/s)/kj",      0.0666 } } }, 	// UNGPMXPOW
  { { {           "cfm/ft2",        1.00 },	{          "(L/s)/m2",     5.08073 } } }, 	// UNCFMPSF
  { { {           "gpm/ft2",        1.00 },	{          "(L/s)/m2",      1.4723 } } }, 	// UNGPMPSF
  { { {                 "$",        1.00 },	{                 "$",        1.00 } } }, 	// UNCOST
  { { {              "$/ft",        1.00 },	{               "$/m",       3.281 } } }, 	// UNCOSTF
  { { {             "$/ft2",        1.00 },	{              "$/m2",      10.764 } } }, 	// UNCOSTSF
  { { {             "W/cfm",        1.00 },	{             "W/L/s",       2.119 } } }, 	// UNWXFLOW
  { { {            "Btu/Wh",        1.00 },	{            "Btu/Wh",        1.00 } } }, 	// UNEER
  { { {                "hr",        1.00 },	{                "hr",        1.00 } } }, 	// UNTIME
  { { {               "min",       60.00 },	{               "min",       60.00 } } }, 	// UNTIME2
  { { {               "sec",     3600.00 },	{               "sec",     3600.00 } } }, 	// UNTIME3
};	// Untab[]

/* end of untab.cpp */
