name: "Build CSE"
description: "Get git info (for version) and build CSE executable"
inputs:
  arch:
    description: Target architecture ("32" or "64" bit)
    default: "32"
  config:
    description: Configuration (Release or Debug bit)
    default: Release
  build_dir:
    description: Relative path to the build directory
    default: build
runs:
  using: composite
  steps:
    - name: Get branch name
      uses: tj-actions/branch-names@v6.4
      id: branch-name
    - name: Install Linux Libraries
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt-get -y install xorg-dev libgl1-mesa-dev
    - name: Save branch name
      run: echo "CI_GIT_BRANCH=${{steps.branch-name.outputs.current_branch}}" >> $GITHUB_ENV
      shell: bash
    - name: Build and Configure
      shell: bash
      run: cmake -DBUILD_ARCHITECTURE=${{ inputs.arch }} -DCONFIGURATION=${{ inputs.config }} -DBUILD_DIRECTORY=${{ inputs.build_dir }} -P cmake/configure-and-build.cmake
