name: "Build CSE"
description: "Get git info (for version) and build CSE executable"
runs:
  using: composite
  steps:
    - name: Get branch name
      uses: tj-actions/branch-names@v6.4
      id: branch-name
    - name: Save branch name
      run: echo "CI_GIT_BRANCH=${{steps.branch-name.outputs.current_branch}}" >> $GITHUB_ENV
      shell: bash
    - name: Build
      shell: cmd
      run: build.bat
