name: "Download CSE artifact"
description: "Download CSE executable built and uploaded in a previous job"
runs:
  using: composite
  steps:
    - name: Download executable artifact
      uses: actions/download-artifact@v2
      with:
        name: CSE.exe
        path: msvc
