name: "Download CSE artifact"
description: "Download CSE executable built and uploaded in a previous job"
runs:
  using: composite
  steps:
    - name: Download executable artifact
      uses: actions/download-artifact@v4
      with:
        name: CSE_windows-2022-32bit_Release
        path: build
