macro(set_build_directory)
    set(BUILDS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/builds)
    if ("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Windows")
        set(OS_ID "windows")
        if (NOT DEFINED COMPILER_ID)
            set(COMPILER_ID "msvc")
        endif ()
        if (NOT DEFINED BUILD_ARCHITECTURE)
            set(BUILD_ARCHITECTURE "32")
        endif ()
        if ("${BUILD_ARCHITECTURE}" STREQUAL "64")
            set(TARGET_VS_ARCHITECTURE x64)
        else ()
            set(TARGET_VS_ARCHITECTURE Win32)
        endif ()
    else ()
        if (NOT DEFINED CONFIGURATION)
            set(CONFIGURATION Release)
        endif ()
        string(TOLOWER "-${CONFIGURATION}" CONFIGURATION_STRING)
        if (NOT DEFINED BUILD_ARCHITECTURE)
            set(BUILD_ARCHITECTURE "64")
        endif ()
        if ("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Darwin")
            set(OS_ID "macos")
            set(COMPILER_ID "appleclang")
        elseif ("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Linux")
            set(OS_ID "linux")
            set(COMPILER_ID "gcc")
        endif ()
    endif ()
    set(BUILD_DIRECTORY "${BUILDS_DIRECTORY}/${OS_ID}-${COMPILER_ID}-${BUILD_ARCHITECTURE}${CONFIGURATION_STRING}")
endmacro()
