macro(set_build_directory)
    set(BUILDS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/builds)
    if ("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Windows")
        if ("${BUILD_ARCHITECTURE}" STREQUAL "64")
            set(TARGET_VS_ARCHITECTURE x64)
            set(BUILD_DIRECTORY ${BUILDS_DIRECTORY}/msvc-64)
        else()
            set(TARGET_VS_ARCHITECTURE Win32)
            set(BUILD_DIRECTORY ${BUILDS_DIRECTORY}/msvc-32)
        endif()
    elseif ("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Darwin")
        if ("${CONFIGURATION}" STREQUAL "Debug")
            set(BUILD_DIRECTORY ${BUILDS_DIRECTORY}/clang-debug)
        else()
            set(BUILD_DIRECTORY ${BUILDS_DIRECTORY}/clang-release)
        endif()
    elseif ("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Linux")
        if ("${CONFIGURATION}" STREQUAL "Debug")
            set(BUILD_DIRECTORY ${BUILDS_DIRECTORY}/gcc-debug)
        else()
            set(BUILD_DIRECTORY ${BUILDS_DIRECTORY}/gcc-release)
        endif()
    endif ()
endmacro()
