name: Build Documentation

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '1.17.2' # The pandoc version to download (if necessary) and use.
      - name: Build docs
        run: rake
        working-directory: doc
      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: doc/output