name: Release

on:
  release:
    types:
      - created

jobs:
  release-cse:
    name: Release ${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.compiler }}-${{ matrix.arch }}bit
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            os_ver: "2022"
            arch: "32"
            compiler: msvc
          - os: windows
            os_ver: "2022"
            arch: "64"
            compiler: msvc
            publish_docs: true
          - os: macos
            os_ver: "14"
            arch: "64"
            compiler: clang
    runs-on: ${{ matrix.os }}-${{ matrix.os_ver }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: "3.13"
      - name: Build CSE
        run: cmake -DBUILD_ARCHITECTURE=${{ matrix.arch }} -DCOMPILER_ID=${{ matrix.compiler }} -DCONFIGURATION=Release -DBUILD_DIRECTORY=build -DBUILD_DOCS_WITH_ALL=ON -P cmake/configure-and-build.cmake
      - name: Package CSE
        run: cmake -P cmake/package.cmake
      - name: Upload executable to release assets
        uses: softprops/action-gh-release@v3
        with:
          files: |
            build/cse-*.zip
            build/cse-*.tar.gz
      - name: Update gh-pages
        if: matrix.publish_docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build
          user_name: 'cse-ci'
          user_email: 'ci@cse.org'
          full_commit_message: "Update docs for ${{ github.event.release.tag_name }}."
