name: Update std140 CSE

# Final
#on:
#  release:
#    types:
#      - created

# For test
on:
  push:
    branches:
      - '140-ci-test'

jobs:
  build-cse:
    name: Build CSE executable
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get branch name
        uses: tj-actions/branch-names@v5
        id: branch-name
      - name: Save branch name
        run: echo "CI_GIT_BRANCH=${{steps.branch-name.outputs.current_branch}}" >> $GITHUB_ENV
      - name: Build
        shell: cmd
        run: build.bat
      - name: Upload executable artifiact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: CSE.exe
          path: msvc/CSE.exe

  std140-exe:
    name: Add new exe to std140
    needs: build-cse
    runs-on: windows-2022
    steps:
    - name: Clone std140-cse repo
      uses: action/checkout@v3
      with:
        repository: cse-sim/std140-cse
        path: test/repo/std140-cse
        ref: add-test-workflow

    # Download artifact and attached to 
    - name: Update and push latest CSE std140-cse repo
      uses: action/checkout@v3
      - run: |
        cp "./msvc/CSE.exe" "./test/repo/std140-cse/CSE.exe"
      #  git config user.name github-actions
      #  git config user.email github-actions@github.com
      #  git add CSE.exe
      #  git commit -m "Update CSE.exe"
      #  git push
